version: "3.9"

services:
  web1:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - mongo
      - valkey
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
    volumes:
      - .:/app
    restart: always

  web2:
    build: .
    ports:
      - "8002:8000"
    depends_on:
      - mongo
      - valkey
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
    volumes:
      - .:/app
    restart: always

  web3:
    build: .
    ports:
      - "8003:8000"
    depends_on:
      - mongo
      - valkey
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
    volumes:
      - .:/app
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web1
      - web2
      - web3


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6380:6379"
    restart: always

volumes:
  mongo_data:
